### ISSUE TITLE
Feature request: wayback machine

### ISSUE THREAD

**Issue by jsta** [ropensci/internetarchive#10]
Add a function for wayback machine queries using [https://archive.org/help/wayback_api.php](https://archive.org/help/wayback_api.php)

If this is beyond the scope of the package please feel free to close.

**Comment by lmullen** [comment]
A package for the Wayback Machine would be a good idea. But since the two APIs are only incidentally related, I think it would be better in a separate package.

**Comment by jsta** [comment]
Started at https://github.com/jsta/wayback
