### ISSUE TITLE
Unable to search for exact phrase

### ISSUE THREAD

**Issue by swood-ecology** [ropensci/internetarchive#14]
I would like to search for an exact phrase, like "forest ecology". When I use the query

`ia_keyword_search("forest ecology")`

it seems equivalent to querying forest AND ecology, not "forest ecology". Is there a syntax available for searching exact phrases?

**Comment by lmullen** [comment]
```
ia_keyword_search('forest ecology')
```

returns 1233 items and is the equivalent of the boolean search.

```
ia_keyword_search('"forest ecology"')
```

returns 404 items and is the phrase search.

See the bottom of the Internet Archive search page for details about searching.

https://archive.org/advancedsearch.php

**Comment by jjjake** [comment]
Thanks @lmullen! : )
