### ISSUE TITLE
Amount of data accessible with this pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/internetarchive#15]
👋 as part of preparing an rOpenSci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to.

Do you have a sense for how much data (e.g., in GB) one can access through this pkg? Are the stats on this page https://archive.org/about/ correct? That is, does this pkg allow user to get all those videos, images, etc, or just some of those items?

**Comment by jjjake** [comment]
I believe that information is only for public data, yes. info@archive.org can confirm.

**Comment by lmullen** [comment]
Hi Scott. That’s an interesting way to think about it that I hadn’t considered before. 

As far as I know, all the files that are publicly downloadable at the Internet Archive should also be downloadable through the API.

**Comment by sckott** [comment]
Okay, thanks Lincoln!
