### ISSUE TITLE
Add CI?

### ISSUE THREAD

**Issue by sckott** [ropensci/internetarchive#3]
@lmullen Can I send a PR with travis integration?

**Comment by lmullen** [comment]
Certainly. I didn't add Travis yet because I haven't written tests since it
is pulling from an API. But if you add Travis, I'll add the tests when I
can.

**Comment by sckott** [comment]
okay, will do

**Comment by lmullen** [comment]
Should we be using the `warnings_are_errors: true` setting?

**Comment by sckott** [comment]
Oh right, i somehow thought that was the default in the new native R lang for travis, but perhaps not

**Comment by lmullen** [comment]
I've added that setting and merged the PR. Thanks @sckott.

**Comment by sckott** [comment]
:+1:
